# Generated by Django 2.2.2 on 2019-06-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.IntegerField(max_length=255, unique=True, verbose_name='uuid')),
                ('type', models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], max_length=255, verbose_name='Type')),
                ('reason', models.TextField(max_length=512, verbose_name='Reason')),
                ('source', models.CharField(choices=[('cards', 'Cards'), ('leader', 'Leader'), ('experiments', 'Experiments')], max_length=255, verbose_name='Source')),
                ('leader_id', models.IntegerField(max_length=255, unique=True, verbose_name='Leader')),
                ('incident_dt', models.DateTimeField(verbose_name='Incident date')),
                ('event_uuid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Event uuid')),
                ('place_uuid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Place uuid')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_dt', models.DateTimeField(verbose_name='Date change')),
                ('system', models.CharField(choices=[('cards', 'Cards'), ('leader', 'Leader'), ('experiments', 'Experiments')], max_length=255, verbose_name='System')),
                ('name', models.CharField(choices=[('initiated', 'Initiated'), ('published', 'Published'), ('consideration', 'Consideration'), ('issued', 'Issued'), ('eliminated', 'Eliminated')], max_length=255, verbose_name='Name')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_cards.Card', verbose_name='card')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
    ]
