# Generated by Django 2.2.2 on 2019-06-27 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256, unique=True, verbose_name='uuid')),
                ('type', models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], max_length=256, verbose_name='Type')),
                ('reason', models.TextField(max_length=512, verbose_name='Reason')),
                ('source', models.CharField(choices=[('cards', 'Cards'), ('leader', 'Leader'), ('experiments', 'Experiments')], max_length=256, verbose_name='Source')),
                ('incident_dt', models.DateTimeField(verbose_name='Incident date')),
                ('event_uuid', models.CharField(blank=True, max_length=256, null=True, verbose_name='Event uuid')),
                ('place_uuid', models.CharField(blank=True, max_length=256, null=True, verbose_name='Place uuid')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256, unique=True, verbose_name='uuid')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_dt', models.DateTimeField(verbose_name='Date change')),
                ('system', models.CharField(choices=[('cards', 'Cards'), ('leader', 'Leader'), ('experiments', 'Experiments')], max_length=256, verbose_name='System')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_cards.Card', verbose_name='card')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_cards.Status', verbose_name='status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Status change',
                'verbose_name_plural': 'Status change',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.ManyToManyField(blank=True, to='red_cards.Status', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Leader'),
        ),
    ]
