# Generated by Django 2.2.2 on 2019-07-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('red', 'Красная карточка'), ('yellow', 'Желтая карточка'), ('green', 'Зеленая карточка')], help_text='тип карточки, string, допустимые значения: [“red”, “yellow”, “green”]', max_length=255, verbose_name='Type'),
        ),
    ]
