# Generated by Django 2.2.2 on 2019-06-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='is public'),
        ),
        migrations.AlterField(
            model_name='status',
            name='change_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date change'),
        ),
    ]
