# Generated by Django 2.2.2 on 2019-06-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='event_uuid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Event uuid'),
        ),
        migrations.AlterField(
            model_name='card',
            name='place_uuid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place uuid'),
        ),
        migrations.AlterField(
            model_name='card',
            name='source',
            field=models.CharField(choices=[('cards', 'Cards'), ('leader', 'Leader'), ('experiments', 'Experiments')], max_length=255, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='card',
            name='uuid',
            field=models.CharField(max_length=255, unique=True, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='status',
            name='uuid',
            field=models.CharField(max_length=255, unique=True, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='system',
            field=models.CharField(choices=[('cards', 'Cards'), ('leader', 'Leader'), ('experiments', 'Experiments')], max_length=255, verbose_name='System'),
        ),
    ]
