# Generated by Django 2.2.2 on 2019-07-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('activity_uuid', models.CharField(max_length=36)),
                ('title', models.CharField(max_length=500)),
                ('capacity', models.CharField(max_length=50)),
                ('place_uuid', models.CharField(max_length=36)),
                ('place_title', models.CharField(max_length=500)),
                ('type_uuid', models.CharField(max_length=36)),
                ('type_title', models.CharField(max_length=500)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
