# Generated by Django 2.2.2 on 2019-06-28 15:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0002_auto_20190627_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='status',
        ),
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.RemoveField(
            model_name='status',
            name='description',
        ),
        migrations.RemoveField(
            model_name='status',
            name='uuid',
        ),
        migrations.AddField(
            model_name='card',
            name='leader_id',
            field=models.IntegerField(default=1, max_length=255, unique=True, verbose_name='Leader'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='red_cards.Card', verbose_name='card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='change_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date change'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='leader_id',
            field=models.IntegerField(default=1, max_length=255, unique=True, verbose_name='Leader'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='system',
            field=models.CharField(choices=[('cards', 'Cards'), ('leader', 'Leader'), ('experiments', 'Experiments')], default='cards', max_length=255, verbose_name='System'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='uuid',
            field=models.IntegerField(max_length=255, unique=True, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('published', 'Published'), ('consideration', 'Consideration'), ('issued', 'Issued'), ('eliminated', 'Eliminated')], default='initiated', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StatusChange',
        ),
    ]
