# Generated by Django 2.2.2 on 2019-07-04 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0002_auto_20190704_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRum',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='идентификатор аудитории', primary_key=True, serialize=False, unique=True, verbose_name='uuid')),
                ('title', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
    ]
