# Generated by Django 2.2.2 on 2019-06-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0003_auto_20190628_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='leader_id',
        ),
    ]
