# Generated by Django 2.2.2 on 2019-07-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uuid', models.CharField(max_length=36)),
                ('unti_id', models.IntegerField()),
                ('reliability', models.DecimalField(decimal_places=3, max_digits=5)),
                ('completeness', models.DecimalField(decimal_places=3, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uuid', models.CharField(max_length=36)),
                ('unti_id', models.IntegerField()),
                ('created_dt', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
