# Generated by Django 2.2.2 on 2019-06-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0005_status_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_cards.Card', verbose_name='card'),
        ),
    ]
