# Generated by Django 2.2.2 on 2019-07-05 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0005_eventattendance_eventenroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='file')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date change')),
                ('status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=255, verbose_name='status')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_cards.Card', verbose_name='card')),
            ],
            options={
                'verbose_name': 'Appeal',
                'verbose_name_plural': 'Appeals',
            },
        ),
    ]
