# Generated by Django 2.2.2 on 2019-07-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0007_auto_20190705_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='last_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('published', 'Published'), ('consideration', 'Consideration'), ('issued', 'Issued'), ('eliminated', 'Eliminated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('recommended', 'Recommended')], default='initiated', max_length=255, verbose_name='Name'),
        ),
    ]
