# Generated by Django 2.2.2 on 2019-07-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0008_card_last_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('published', 'Published'), ('consideration', 'Consideration'), ('issued', 'Issued'), ('eliminated', 'Eliminated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('recommended', 'Recommended')], default='initiated', max_length=255, verbose_name='Last Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='leader_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
