# Generated by Django 2.2.2 on 2019-07-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0008_card_last_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='leader_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
