# Generated by Django 2.2.2 on 2019-07-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0011_status_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='system',
            field=models.CharField(choices=[('cards', 'Cards'), ('leader', 'Leader'), ('cards-transform', 'Cards-transform'), ('experiments', 'Experiments')], max_length=255, verbose_name='System'),
        ),
    ]
