# Generated by Django 2.2.2 on 2019-07-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0013_auto_20190709_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='system',
            field=models.CharField(choices=[('cards', 'Cards'), ('api', 'Api'), ('leader', 'Leader'), ('cards-transform', 'Cards-transform'), ('cards-repayment', 'Cards-repayment'), ('experiments', 'Experiments')], max_length=255, verbose_name='System'),
        ),
    ]
