# Generated by Django 2.2.2 on 2019-07-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0015_auto_20190711_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='red_cards.Status', verbose_name='Status'),
        ),
    ]
