# Generated by Django 2.2.2 on 2019-07-14 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0015_auto_20190714_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(verbose_name='Description')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='file')),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_cards.Appeal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
