# Generated by Django 2.2.2 on 2019-07-12 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0016_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='red_cards.Status', verbose_name='Status'),
        ),
    ]
