# Generated by Django 2.2.2 on 2019-07-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0016_manual_fix_old_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='system',
            field=models.CharField(choices=[('cards-assistant', 'Cards-assistant'), ('cards-consideration', 'Cards-consideration'), ('cards-appeal', 'Cards-appeal'), ('api', 'Api'), ('leader', 'Leader'), ('cards-transform', 'Cards-transform'), ('cards-repayment', 'Cards-repayment'), ('experiments', 'Experiments'), ('legacy', 'From old site version')], max_length=255, verbose_name='System'),
        ),
    ]
