# Generated by Django 2.2.2 on 2019-07-14 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0016_appealcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealcomment',
            name='seen_by_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
