# Generated by Django 2.2.2 on 2019-07-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0018_auto_20190716_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hash', models.CharField(max_length=255, unique=True, verbose_name='Hash of tag')),
                ('name', models.CharField(max_length=255, verbose_name='Name of tag')),
            ],
            options={
                'verbose_name': 'Appeal Tag',
                'verbose_name_plural': 'Appeal Tags',
            },
        ),
        migrations.AlterModelOptions(
            name='appealcomment',
            options={'verbose_name': 'Appeal Comment', 'verbose_name_plural': 'Appeal Comments'},
        ),
    ]
