# Generated by Django 2.2.2 on 2019-07-16 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0019_auto_20190716_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='red_cards.AppealTag', verbose_name='Тег'),
        ),
    ]
