# Generated by Django 2.2.2 on 2019-09-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_cards', '0021_manual_insert_5_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='appealcomment',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
    ]
