# Generated by Django 2.2.2 on 2019-06-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0002_auto_20190529_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(default='NA', max_length=255),
            preserve_default=False,
        ),
    ]
